import { getBusinessSettings } from '@/data/settings'

interface ReportLayoutProps {
  title: string
  subtitle?: string
  icon?: React.ReactNode
  children: React.ReactNode
  toolbar?: React.ReactNode
}

export function ReportLayout({ title, subtitle, icon, children, toolbar }: ReportLayoutProps) {
  return (
    <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-5">
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-3">
          {icon && (
            <div className="size-10 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center shrink-0 mt-0.5">
              {icon}
            </div>
          )}
          <div>
            <h1 className="text-xl sm:text-2xl font-semibold tracking-tight">{title}</h1>
            {subtitle && <p className="text-sm text-muted-foreground mt-1">{subtitle}</p>}
          </div>
        </div>
        <div className="flex items-center gap-2">{toolbar}</div>
      </div>

      {children}

      <div className="text-[10px] text-muted-foreground border-t border-border pt-3 flex items-center justify-between">
        <span>Generated: {new Date().toLocaleDateString('en-PK', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</span>
        <span>Generated by: {getBusinessSettings().businessName}</span>
      </div>
    </div>
  )
}
