interface InvoiceFooterProps {
  notes?: string | null
  receipt?: Record<string, any>
}

/** Footer — notes, thank-you message, terms, & signatures, all controlled by receipt toggles */
export default function InvoiceFooter({ notes, receipt }: InvoiceFooterProps) {
  const r = receipt || {}

  return (
    <div className="mt-8 pt-4 border-t border-gray-300 text-center">
      {notes && <p className="text-sm text-gray-600 mb-2 italic">{notes}</p>}

      {r.header_text && (
        <p className="text-sm text-gray-500 font-medium">{r.header_text}</p>
      )}

      {r.footer_text && (
        <p className="text-xs text-gray-400 mt-1 whitespace-pre-line">{r.footer_text}</p>
      )}

      {r.terms_conditions && (
        <div className="mt-3 pt-3 border-t border-gray-200">
          <p className="text-[10px] text-gray-400 uppercase tracking-wide mb-1">Terms &amp; Conditions</p>
          <p className="text-xs text-gray-500 whitespace-pre-line">{r.terms_conditions}</p>
        </div>
      )}

      {/* Signatures */}
      <div className="flex justify-between mt-6 text-xs text-gray-500">
        {r.show_customer_signature && (
          <div className="text-center">
            <div className="w-32 border-t border-gray-400 pt-1">Customer Signature</div>
          </div>
        )}
        {r.show_authorized_signature && (
          <div className="text-center">
            <div className="w-32 border-t border-gray-400 pt-1">Authorized Signature</div>
          </div>
        )}
        {r.show_received_by && (
          <div className="text-center">
            <div className="w-32 border-t border-gray-400 pt-1">Received By</div>
          </div>
        )}
      </div>

      <p className="text-[10px] text-gray-400 mt-4">Generated by Invenos POS</p>
    </div>
  )
}
