<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductPackaging extends Model
{
    protected $table = 'product_packaging';

    protected $fillable = [
        'product_id',
        'container_unit_id',
        'contains_unit_id',
        'quantity',
        'level',
    ];

    protected $casts = [
        'quantity' => 'float',
        'level' => 'integer',
    ];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function containerUnit()
    {
        return $this->belongsTo(ProductUnit::class, 'container_unit_id');
    }

    public function containsUnit()
    {
        return $this->belongsTo(ProductUnit::class, 'contains_unit_id');
    }

    /**
     * The derived selling unit that was generated from this packaging row.
     * Only the "container" side generates a selling unit (the "contains" side
     * either has its own row or is generated by a higher-level row).
     */
    public function derivedSellingUnit()
    {
        return $this->hasOne(SellingUnit::class, 'packaging_id');
    }
}
